#!/usr/bin/env bash
# Connects to the server
apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
