#!/usr/bin/env bash
# Connects to the server

apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
