#!/usr/bin/env bash
# install nginx to create html pages - redirection
Redirigir="\\\t\tlocation /redirect_me {\n\t\t\t return 301 https://www.youtube.com/watch?v=CB3H05OhVDI;\n\t\t}\n"
File="/etc/nginx/sites-available/default"
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "35i $Redirigir" $File
sudo service nginx restart
