#!/usr/bin/env bash
# install nginx to create html pages - redirection
Redirigir="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
File="/etc/nginx/sites-available/default"
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "35i $Redirigir" $File
sudo service nginx restart
