#!/usr/bin/env bash
# install load balancer
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.7
sudo apt-get -y update
sudo apt-get -y install haproxy=1.7.\*
{
    echo -e "\nlisten firstbalance"
    echo -e "\tbind :80"
    echo -e "\tbalance roundrobin"
    echo -e "\tserver gc-1482-web-01-1596431688 34.73.198.109"
    echo -e "\tserver gc-1482-web-02-1597382468 35.231.28.80"
} >>/etc/haproxy/haproxy.cfg
sudo service haproxy restart
