#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'sudo rm -f /var/run/holbertonscript.pid; exit' SIGQUIT
trap 'echo "I hate the kill command";sudo rm -f /var/run/holbertonscript.pid; exit' SIGTERM
sudo touch /var/run/holbertonscript.pid
a=0
while [ $a ]
do
    echo "To infinity and beyond"
    sleep 2
done
